#!/usr/bin/env bash
# get information about Holberton student domains


declare -a default_subs
declare -a record
default_subs=(www lb-01 web-01 web-02)


get_address () {
	dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/{print $4"\t"$5}'
}

if (( $# > 1 )); then
	record=($(get_address "${2}.${1}"))
	echo "The subdomain ${2} is a ${record[0]} record and points to ${record[1]}"
else
	for sub in "${default_subs[@]}"; do
		record=($(get_address "${sub}.${1}"))
		echo "The subdomain ${sub} is a ${record[0]} record and points to ${record[1]}"
	done
fi
