#!/usr/bin/env bash
# Change ip request
sudo cp /etc/hosts ./hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' hosts.new
sudo cp -f ./hosts.new /etc/hosts
sudo cp /etc/nsswitch.conf ./nss.new
sed -i 's/hosts:.*/hosts: files dns/' nss.new
sudo cp -f ./nss.new /etc/nsswitch.conf